spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${USERNAME_DB}
    password: ${PASSWORD_DB}
    url: ${URL_DB}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  application:
    name: babilonia
