spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTHORIZATION_SERVE}

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${USERNAME_DB}
    password: ${PASSWORD_DB}
    url: ${URL_DB}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  application:
    name: babilonia

server:
  port: 8081

keycloak:
  realm: ${REALM}
  client-id: ${CLIENT_ID}
  username: ${USERNAME}
  password: ${PASSWORD}
  server-url: ${SERVER_URL}
springdoc:
  show-actuator: true
